
services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: muhira
      POSTGRES_PASSWORD: muhira123
      POSTGRES_DB: muhira
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U muhira"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: muhira
      DB_PASSWORD: muhira123
      DB_NAME: muhira
      PORT: 3000
    ports:
      - "8080:3000"   # accessible at localhost:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
